### ISSUE TITLE
Create lambda function that uses user location input and returns baaqmd representative

### ISSUE THREAD

**Issue by sent-hil** [sfbrigade/planetbot#7]

**Comment by techieshark** [comment]
Great, yeah I know where this is - it’s in my baaqmd-frontend repo but I was going to do a refactor and pull it out into its own node module so we either have a code example to build off or we can build a tiny api that our lambda function can hit.

**Comment by sent-hil** [comment]
@techieshark not that, remember I ported that code to Go? It just hit the google maps api and returned which country you were in. But I'm ok with a Nodejs lambda function for this!

**Comment by techieshark** [comment]
I was thinking we might want a little api that takes an address and returns the reps (in Json array) for that location.

**Comment by sent-hil** [comment]
We can do that, but then we'll have to host that on a server somewhere. If it's a lambda function then it'll be serverless.

Each of the lambda functions are independent of each other so we can have this in Node and rest in Go or python or any combo really.

**Comment by techieshark** [comment]
OK, done.

The AWS [Node.js lambda](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html) is in [this repo](https://github.com/techieshark/baaqmd-rep-serverless).
A little bit of JS code it depends on is in [this one](https://github.com/techieshark/baaqmd-reps). 


---
# Notes

Saved to console under Functions > baaqmdLookup

What I see when testing (create an event with {city: 'San Francisco', county: 'San Francisco'}
![image](https://user-images.githubusercontent.com/1072292/35213523-c772041c-ff12-11e7-867b-b745201bf523.png)


The AWS lambda is vanilla JS now, but might [switch to ES6](http://www.rricard.me/es6/aws/lambda/nodejs/2015/11/29/es6-on-aws-lambda.html) later.

**Comment by techieshark** [comment]
Though - do we want the response to be simple human friendly text, like their name(s)? Something to chat about wed.
